spring:
    #default 설정임
#    thymeleaf:
#      prefix: classpath:/templates/
#      suffix: .html

    datasource:
      url: jdbc:h2:tcp://localhost/~/jpashop
      username: sa
      password:
      driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        #애플리케이션 실행시점에 DB재생성
        ddl-auto: create
      properties:
        hibernate:
          #System.out
          #show_sql: true
          format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
    jpashop:
      jpabook: debug